"""empty message

Revision ID: 376cad8649cc
Revises: 6dbae7a5ca5d
Create Date: 2024-03-26 21:04:16.148199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376cad8649cc'
down_revision = '6dbae7a5ca5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailCode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailCode')
    # ### end Alembic commands ###
