"""empty message

Revision ID: cc9102b340b7
Revises: a35f6d988b34
Create Date: 2024-04-12 23:06:13.316245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc9102b340b7'
down_revision = 'a35f6d988b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baiducookie', schema=None) as batch_op:
        batch_op.alter_column('cookies',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('userinfbybaidu', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfbybaidu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('baiducookie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cookies',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
