"""empty message

Revision ID: fd77061b80c9
Revises: e0c64b45ec0b
Create Date: 2024-04-16 11:15:21.152824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd77061b80c9'
down_revision = 'e0c64b45ec0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfobybaidu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cookies', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('userinfobydouding', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfobydouding', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('userinfobybaidu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cookies')

    # ### end Alembic commands ###
